name: "GraphQL Compose: Metatags"
description: "Metatag information added to GraphQL schema."
type: module
core_version_requirement: ^9 || ^10
dependencies:
  - graphql_compose:graphql_compose
  - metatag:metatag
package: GraphQL Compose
hidden: false
