name: "GraphQL Compose: Node Type"
description: "Enable node types."
type: module
core_version_requirement: ^9 || ^10
dependencies:
  - graphql_compose:graphql_compose
package: GraphQL Compose
hidden: false
