<?php

/**
 * @file
 * Add connection edges to entity bundles.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\ContentEntityTypeInterface;

/**
 * Implements hook_graphql_compose_entity_type_form_alter().
 */
function graphql_compose_edges_graphql_compose_entity_type_form_alter(array &$form, FormStateInterface $form_state, array $settings): void {
  $base_type = $form_state->get('base_type');

  if ($base_type instanceof ContentEntityTypeInterface) {
    $form['graphql_compose']['edges_enabled'] = [
      '#type' => 'checkbox',
      '#title' => t('Enable multiple query'),
      '#default_value' => $settings['edges_enabled'] ?? FALSE,
      '#description' => t('Edge connections enable loading multiple entities at once with a cursor.'),
    ];
  }
}

/**
 * Implements graphql_compose_entity_type_form_submit_alter().
 */
function graphql_compose_edges_graphql_compose_entity_type_form_submit_alter(array $form, FormStateInterface $form_state, array &$settings): void {
  if (isset($form['graphql_compose']['edges_enabled'])) {
    $settings['edges_enabled'] = (bool) $form_state->getValue([
      'graphql_compose',
      'edges_enabled',
    ]);
  }
}
