<?php

/**
 * @file
 * Add connection users to entity bundles.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_graphql_compose_entity_base_fields_alter().
 */
function graphql_compose_users_graphql_compose_entity_base_fields_alter(array &$fields, string $entity_type_id): void {
  if ($entity_type_id === 'node') {
    $fields['uid'] = [
      'type' => 'entity_owner',
      'name_sdl' => 'author',
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add settings to account configuration page.
 */
function graphql_compose_users_form_user_admin_settings_alter(&$form, FormStateInterface $form_state): void {
  $entity_type = \Drupal::entityTypeManager()->getDefinition('user');
  $form_state->set('entity_type', $entity_type);
  $form_state->set('base_type', $entity_type);

  _graphql_compose_entity_type_settings_alter($form, $form_state);

  $form['graphql_compose']['#open'] = TRUE;
}
