<?php

/**
 * @file
 * Add connection users to entity bundles.
 */

declare(strict_types=1);

/**
 * Implements hook_graphql_compose_entity_base_fields_alter().
 */
function graphql_compose_users_graphql_compose_entity_base_fields_alter(array &$fields, string $entity_type_id): void {
  if ($entity_type_id === 'node') {
    $fields['uid'] = [
      'type' => 'entity_owner',
      'name_sdl' => 'author',
    ];
  }
}
