<?php

/**
 * @file
 * Update functions for the CDN module.
 */

/**
 * Force container & cache rebuild upon upgrading from 8.x-3.x to 4.x.
 */
function cdn_update_9401() {
}

/**
 * Add the new "prevent_duplicate_content" setting, set it to its default initial value.
 */
function cdn_update_8004() {
  \Drupal::configFactory()->getEditable('cdn.settings')->set('prevent_duplicate_content', TRUE)->save();
}
