<?php

/**
 * Implements hook_theme_registry_alter().
 */
function next_image_styles_theme_registry_alter(&$theme_registry)
{
  // Tell the theme system to look in templates in our module.
  $theme_registry['focal_point_preview_page']['theme paths'] = array(0 => \Drupal::service('extension.list.module')->getPath('next_image_styles') . '/templates');
  $theme_registry['focal_point_preview_page']['theme path'] = \Drupal::service('extension.list.module')->getPath('next_image_styles') . '/templates';
  $theme_registry['focal_point_preview_page']['path'] = \Drupal::service('extension.list.module')->getPath('next_image_styles') . '/templates';
  // Tell the theme system to use our template file.
  $theme_registry['focal_point_preview_page']['template'] = 'focal-point-preview-page';
}
