name: 'GraphQL Compose'
description: 'Toolkit for composing GraphQL schemas in Drupal.'
type: module
core_version_requirement: ^9.5 || ^10
php: 8.1
dependencies:
  - graphql:graphql
  - drupal:node
package: GraphQL Compose
hidden: false
configure: graphql_compose.schema

# Information added by Drupal.org packaging script on 2023-06-19
version: '2.0.0-beta8'
project: 'graphql_compose'
datestamp: 1687159784
