name: "GraphQL Compose: Routes Extra"
description: "Load entites by path."
type: module
core_version_requirement: ^9 || ^10
dependencies:
  - graphql_compose:graphql_compose
  - domain:domain
package: GraphQL Compose
hidden: false
