<?php

/**
 * @file
 * Add connection routes to entity bundles.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_graphql_compose_entity_type_form_alter().
 */
function graphql_compose_routes_extra_graphql_compose_entity_type_form_alter(array &$form, FormStateInterface $form_state, array $settings):void {
  $base_type = $form_state->get('base_type');
  if ($base_type instanceof EntityTypeInterface && $base_type->hasLinkTemplate('canonical')) {
    $form['graphql_compose']['routes_enabled'] = [
      '#type' => 'checkbox',
      '#title' => t('Enable loading by route'),
      '#default_value' => $settings['routes_enabled'] ?? FALSE,
      '#description' => t('Enable this type to load via URL using the route() query.'),
    ];
  }
}

/**
 * Implements graphql_compose_entity_type_form_submit_alter().
 */
function graphql_compose_routes_extra_graphql_compose_entity_type_form_submit_alter(array $form, FormStateInterface $form_state, array &$settings): void {
  if (isset($form['graphql_compose']['routes_enabled'])) {
    $settings['routes_enabled'] = (bool) $form_state->getValue([
      'graphql_compose',
      'routes_enabled',
    ]);
  }
}
