require_login.settings:
  type: config_object
  label: "Login requirements"
  mapping:
    login_path:
      type: label
      label: "Login path"
    login_message:
      type: text
      label: "Login message"
    login_destination:
      type: label
      label: "Login destination"
    requirements:
      type: sequence
      label: "Requirements"
      sequence:
        type: condition.plugin.[id]
        label: "Condition"
    extra:
      type: mapping
      label: "Extra options"
      mapping:
        include_403:
          type: boolean
          label: "Include 403 (access denied) page"
        include_404:
          type: boolean
          label: "Include 404 (not found) page"
