name: 'GraphQL Compose: Routes'
description: 'Enable loading canonical entities by path and add route information to links.'
type: module
core_version_requirement: ^9.5 || ^10
php: 8.1
dependencies:
  - graphql_compose:graphql_compose
  - drupal:path
package: GraphQL Compose
hidden: false

# Information added by Drupal.org packaging script on 2023-08-22
version: '2.0.0-beta10'
project: 'graphql_compose'
datestamp: 1692668670
