name: "GraphQL Compose: Menus"
description: "Expose menus and links."
type: module
core_version_requirement: ^9 || ^10
dependencies:
  - core:menu_link_content
  - graphql_compose:graphql_compose
  - graphql_compose:graphql_compose_routes_extra
package: GraphQL Compose
hidden: false
